### ISSUE TITLE
Catch2 issue on V2.3.0

### ISSUE THREAD

**Issue by nazzak** [tplgy/cppcodec#74]
Hi,
Catch2 doesn't compile with gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1) :

cppcodec-src/test/catch/single_include/catch2/catch.hpp:7485:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
 7485 |     constexpr static std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/sigstksz.h:24,

This is known issue by the maintainers.
Could you please update the gitmodule to point to a more recent release version ?

Thank you in advance
